### ISSUE TITLE
what is the LICENSE for camus

### ISSUE THREAD

**Issue by harshach** [linkedin/camus#159]
could you please add LICENSE on camus.

**Comment by HenryCaiHaiying** [comment]
@kengoodhope , I wasn't around when camus was first open sourced.  Ken, do you know what type of license did you guys decided at that time?

**Comment by harshach** [comment]
@kengoodhope  could you please let us know whats the license of camus is . thanks.

**Comment by HenryCaiHaiying** [comment]
The license would be apache 2.0.

**Comment by harshach** [comment]
Thanks @HenryCaiHaiying . If you don't mind can you include LICENSE file in the source dir. That will be great.

**Comment by HenryCaiHaiying** [comment]
We will need to work with our legal department to sort out the licnese/notice and our dependency to other 3rdParty libraries, this might take some time.
