### ISSUE TITLE
EtlMultiOutputRecordWriter compile error

### ISSUE THREAD

**Issue by cbcwebdev** [linkedin/camus#165]
master has EtlMultiOutputRecordWriter::write@L70 referencing TaskAttemptContext, intended to be Mapper.Context

**Comment by HenryCaiHaiying** [comment]
I think in hadoop1, we probably use should use Mapper.Context, this needs to be fixed.

**Comment by cbcwebdev** [comment]
#166 appears to be the same issue. I can send a pull request tomorrow. You're correct, hadoop2 is a non-issue

**Comment by HenryCaiHaiying** [comment]
Yes, if you got time, please send a pull request.
