### ISSUE TITLE
camus does not build

### ISSUE THREAD

**Issue by davidchen322** [linkedin/camus#166]
$ git clone https://github.com/linkedin/camus.git
$ cd camus
$ mvn clean package

----
... lots of output ...

[INFO] 4 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/dchen/camus/camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlMultiOutputRecordWriter.java:[70,16] cannot find symbol
  symbol:   method getCounter(java.lang.String,java.lang.String)
  location: variable context of type org.apache.hadoop.mapreduce.TaskAttemptContext
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Camus Parent ....................................... SUCCESS [  0.646 s]
[INFO] Camus API. ......................................... SUCCESS [  1.569 s]
[INFO] Camus schema registry. ............................. SUCCESS [  0.728 s]
[INFO] Camus Kafka producer ............................... SUCCESS [  0.865 s]
[INFO] Camus ETL to move data from Kafka to Hadoop. ....... FAILURE [  0.961 s]
[INFO] Camus schema registry. ............................. SKIPPED
[INFO] Camus Examples ..................................... SKIPPED
[INFO] Camus compaction code small files produced Camus ... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.967 s
[INFO] Finished at: 2015-01-27T13:44:12-05:00
[INFO] Final Memory: 26M/328M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project camus-etl-kafka: Compilation failure
[ERROR] /home/dchen/camus/camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlMultiOutputRecordWriter.java:[70,16] cannot find symbol
[ERROR] symbol:   method getCounter(java.lang.String,java.lang.String)
[ERROR] location: variable context of type org.apache.hadoop.mapreduce.TaskAttemptContext
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :camus-etl-kafka

**Comment by davidchen322** [comment]
If I replace the hadoop-client version with the 1st stable 2.x.x version (2.2.0), the build works:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Camus Parent ....................................... SUCCESS [  0.614 s]
[INFO] Camus API. ......................................... SUCCESS [  1.969 s]
[INFO] Camus schema registry. ............................. SUCCESS [  0.916 s]
[INFO] Camus Kafka producer ............................... SUCCESS [  0.915 s]
[INFO] Camus ETL to move data from Kafka to Hadoop. ....... SUCCESS [ 24.841 s]
[INFO] Camus schema registry. ............................. SUCCESS [  2.406 s]
[INFO] Camus Examples ..................................... SUCCESS [ 10.733 s]
[INFO] Camus compaction code small files produced Camus ... SUCCESS [  1.245 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.852 s
[INFO] Finished at: 2015-01-27T13:50:13-05:00
[INFO] Final Memory: 77M/602M
[INFO] ------------------------------------------------------------------------

**Comment by HenryCaiHaiying** [comment]
Looks like this line doesn't work with hadoop1 any more, we probably need to fix it.  Are you working with hadoop1 or hadoop2?

**Comment by HenryCaiHaiying** [comment]
Or if change that line to:

        ((Mapper.Context) context).getCounter("total", "skip-old").increment(1);

Does that compile under hadoop 1?

**Comment by mahanteshakumbar** [comment]
Hi All ,
I am using Hadoop 2.2.0.2.0.6.0-102 version and kafka-0.8.0-beta1-src 
and deploying camus 
when i ran cmd 
mvn clean package
getting bellow error
Tests run: 29, Failures: 0, Errors: 3, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Camus Parent ...................................... SUCCESS [0.938s]
[INFO] Camus API. ........................................ SUCCESS [1.671s]
[INFO] Camus schema registry. ............................ SUCCESS [0.899s]
[INFO] Camus Kafka producer .............................. SUCCESS [1.099s]
[INFO] Camus ETL to move data from Kafka to Hadoop. ...... FAILURE [13.663s]
[INFO] Camus schema registry. ............................ SKIPPED
[INFO] Camus Examples .................................... SKIPPED
[INFO] Camus compaction code small files produced Camus .. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.530s
[INFO] Finished at: Fri Mar 06 16:24:34 IST 2015
[INFO] Final Memory: 17M/151M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project camus-etl-kafka: There are test failures.
[ERROR] 
[ERROR] Please refer to /usr/local/camus-master/camus-etl-kafka/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :camus-etl-kafka

Please help me how to solve

**Comment by zliu41** [comment]
Please look into the surefire-reports, let me know which test failed, and what the error message was.

**Comment by mahanteshakumbar** [comment]
Thanku for replay 
com.linkedin.camus.etl.kafka.CamusJobTest  is failing 
 and i am not able understand kafka.Camusjob is hitting to localhost 
15/03/09 11:33:25 INFO kafka.CamusJob: The requests from kafka metadata are: 
[topic_1	uri:tcp://localhost:42574	leader:1	partition:0	earliest_offset:0	offset:0	latest_offset:10	avg_msg_size:1024	estimated_size:10240, topic_2	uri:tcp://localhost:42574	leader:1	partition:0	earliest_offset:0	offset:0	latest_offset:10	avg_msg_size:1024	estimated_size:10240, topic_3	uri:tcp://localhost:42574	leader:1	partition:0	earliest_offset:0	offset:0	latest_offset:10	avg_msg_size:1024	estimated_size:10240]
15/03/09 11:33:25 INFO network.Processor: Closing socket connection to /127.0.0.1.
15/03/09 11:33:25 INFO compress.CodecPool: Got brand-new compressor
15/03/09 11:33:25 INFO kafka.CamusJob: topic_1	uri:tcp://localhost:42574	leader:1	partition:0	earliest_offset:0	offset:0	latest_offset:10	avg_msg_size:1024	estimated_size:10240
15/03/09 11:33:25 INFO kafka.CamusJob: topic_2	uri:tcp://localhost:42574	leader:1	partition:0	earliest_offset:0	offset:0	latest_offset:10	avg_msg_size:1024	estimated_size:10240
15/03/09 11:33:25 INFO kafka.CamusJob: topic_3	uri:tcp://localhost:42574	leader:1	partition:0	earliest_offset:0	offset:0	latest_offset:10	avg_msg_size:1024	estimated_size:10240
15/03/09 11:33:25 INFO mapred.JobClient: Running job: job_local_0004

Please tell me where to chnage localhost to namenode
2)
error message
runJobWithErrors(com.linkedin.camus.etl.kafka.CamusJobTest)  Time elapsed: 1.103 sec  <<< ERROR!
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:386)
	at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:226)
	at com.linkedin.camus.etl.kafka.CamusJobTest.runJobWithErrors(CamusJobTest.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
