### ISSUE TITLE
Data loss and How Files are Committed to Hadoop FS Issue 

### ISSUE THREAD

**Issue by bmistry13** [linkedin/camus#189]
Hi Camus Team,

We have observed that there is issue with commit (following line eg if file rename fails due to FS unsuitability or any unknown reason ), but the offset file is still committed, so data is loss because offset is already fast-forward and commit but not actual data.  

https://github.com/linkedin/camus/blob/master/camus-etl-kafka/src/main/java/com/linkedin/camus/etl/kafka/mapred/EtlMultiOutputCommitter.java#L152

It would be better to have transaction based commit when all file rename succeeds then entire mapper task succeed or rename failed files offset should not be committed to HDFS meta data directory.

Would appreciate if you guys can look into this issue and also suggest/recommend how to fix this issue ?

Thanks,

Bhavesh

**Comment by zliu41** [comment]
Hi Bhavesh,

Since camus commits data files before committing offset, if commitFile() throws an exception, it shouldn't continue to commit the offset file. In your case did commitFile() silently failed with no exception?

Ziyang

**Comment by bmistry13** [comment]
@zliu41 ,

Yes,  Rename returns false.  

Thanks,

Bhavesh

**Comment by zliu41** [comment]
Right, rename() and mkdirs() may return false rather than throw exception on failure. So we can throw IOException when they return false. Any other suggestions?

**Comment by HenryCaiHaiying** [comment]
Sounds good to me.

BMistry, do you want to fix it?

________________________________

**Comment by bmistry13** [comment]
That is fine I can fix it up.  But this has to be done every where in code base.  Also there is other problems as  well please refer to http://answers.mapr.com/questions/162562/volume-issues-end-of-file-javaioioexception-file-i.html (related to hadoop FS).

In which, I have to do two steps to commit a file to final destination  1) copy from _temporary dir to [volume]/_temporary/ and then move file  or rename to final name within same volume ([volume]/filename) .

The above two are almost relevant. Also, I feel we need interface to here to inject and control how files are being committed.   

Any idea about this also ?

Thanks,

Bhavesh

**Comment by HenryCaiHaiying** [comment]
Bhavesh,

Is your final directory outside HDFS?  That's why rename failed?  How often does it fail?  We actually don't that problem in Linkedin when our final directory is still in HDFS.

Copy + rename would incur extra file copy overhead, (and does the rename between two filesystems are doing the same thing anyway?)  it seems it might be better to either retry the rename (if the failure chance is not that high), or falls back to copy+rename if the rename failed.
________________________________

**Comment by Kaiserchen** [comment]
Hello,

I am actually thinking about this for some time now. We never encountered these problems so far as the critical path is still quite short, but the possibility of having some sort of issue between commiting data and offsets files always troubled me. 

I am actually thinking of rewriting this part to encode the last offset pulled into the filename where the output is beeing moved to. This raises quite a few other problems: 
1. Wich partitions to search for the highest offset as it can be quite many.
2. During compaction of smaller files into bigger files, this offset needs to be tracked correctly, which is quite tricky, especially dealing with a pull job launched concurrently.

I felt that this issue might be a good place to aks for your opinions regarding this. My personal feeling is that the pulling can be made "more correct" in terms of using atomic operations provided by the namenode. The logic gets quite more complicated to make this happen, and I feel its hard to judge if its worth implementing.

Thank you for your opinions in advance

Jan

**Comment by bmistry13** [comment]
HI Henry,
It is same hadoop FS (MapR).  But user that runs the hadoop camus job has volume A and actual data goes to Volume B.
So what happens is camus copy the data from Kafka -- user volume metadata directory _temporary dir --> FS.rename ---Fails due cross volume rename.

Hence, we have to employ the two steps commit (which I think is short term solution and over head as you mentioned to me).  The longterm is to write to  Volume B/temp and rename (we are still on hadoop 1.x.x API).  So ability to write to different temp directory from same MAPPER job and then rename will have less issue,  ( I am in testing face) but you have to assume failure for large cluster hadoop node anything that FS API goes wrong retry and retry.  

Here is more info:
http://doc.mapr.com/display/MapR/Introduction+to+Volumes

Volume is easy to manage from the hadoop Ops prospective (but nightmare from the Dev prospective)  when you have large data.

I hope this give better prospective on problem at hand.

Thanks,
Bhavesh

**Comment by bmistry13** [comment]
Also, guys if you can help with debugging why camus output files have following issue when read by other process on hadoop FS:
1) Caused by: java.io.EOFException Unterminated or unclosed files.
2) Caused by: java.io.IOException: File is corrupt!

Why  file generated by camus  is unterminated and/or unclosed ?  Why corrupted (possibly FS issue but ?

Do you think it is worth running md5Hash (configurable option) and compare source vs destination ?  Any other option to solve this as well ?

Thanks,
Bhavesh

**Comment by bmistry13** [comment]
@Kaiserchen ,

Can we store the offset in external system (Just like High Level ZK or new approach brokers itself) ?  By default HDFS is fine.

This will be easy to manage and monitor rather than (interpreting camus offset HDFS files (previous etc) for monitoring lags and problem with camus job.

Thanks,

Bhavesh 


Thanks,
Bhavesh

**Comment by HenryCaiHaiying** [comment]
Does the user only have access to volume A but not B?  If that's the case, how does the code able to do rename later?

I think the location of the temp file generated during camus pull can be controlled by:

mapreduce.output.fileoutputformat.outputdir

if you set that property to a location in volume B, what would happen?

________________________________

**Comment by bmistry13** [comment]
Hi @ HenryCaiHaiying,

User have access to both volumes or directory.   It is not "mapreduce.output.fileoutputformat.outputdir"  what we need is all temp files created under final destination path not under metadata or single directory for temp.

Because this will not work when you have to time data across time  bounty (e.g you have 1 hr directory structure for your log data. The data come late or early for any camus job so we will end up with same issue moving across volume but data arrive late or early so can not have single or same path for all temp files for give camus job run.  It must go to final directory/temp which is different path based on decoder (or in this case timestamp of log line).

That also brings up the hadoop speculative execution and committing file and clean-up of mapper or hadoop job.

Thanks,
Bhavesh

**Comment by bmistry13** [comment]
@HenryCaiHaiying  @Kaiserchen @zliu41,  @kengoodhope,

Any good suggestions on how to commit a file and checking that src matches with destination ? 

Your suggestions or feedbacks are most welcome.

Thanks,
Bhavesh

**Comment by HenryCaiHaiying** [comment]
This is what's in our server log:


2015-03-13 00:47:08,450 INFO [Thread-5] com.linkedin.camus.etl.kafka.mapred.EtlMultiOutputFormat: Moved file from: hdfs://eat1-etorinn01.grid.linkedin.com:9000/jobs/kafkaetl/camus-0.8/2015-03-13-00-44-36/_temporary/1/_temporary/attempt_1424755100717_178507_m_000000_0/data.AdOptimizationEvent.0.0.1426204800000-m-00000.avro to: /data/tracking/AdOptimizationEvent/hourly/2015/03/12/17/AdOptimizationEvent.1426207628.0.63225.0.1426204800000.avro



Both the from and to location /jobs/kafkaetl/camus-0.8 and /data/tracking/... are specified from config property: etl.execution.base.path and etl.destination.path, can you configure them to be on the same volume?


________________________________

**Comment by bmistry13** [comment]
@zliu41 , @HenryCaiHaiying , @Kaiserchen, @kengoodhope 

We have following  situation and volumes are hourly: 
 
etl.execution.base.path=/jobs/kafkaetl/camus-0.8 [call this metadata volume] 
etl.destination.path.path=/data/tracking/ [ call this data volume] 
 
And what we have are volumes per (day) but explain in hourly: 

File generated: 
data/tracking/AdOptimizationEvent/hourly/2015/03/12/17/AdOptimizationEvent.1426207628.0.63225.0.1426204800000.avro 
 
When camus job is running at "17" hour, we will have data coming in for either 16 or 18 or 17 hour (time bountry, so we will be copying from volume to volume any ways. Hence, it does not work plus offset needs to be store in single volume.) 
 
data/tracking/AdOptimizationEvent/hourly/2015/03/12/16/AdOptimizationEvent.1426207628.0.63225.0.1426204800000.avro 
 
data/tracking/AdOptimizationEvent/hourly/2015/03/12/18/AdOptimizationEvent.1426207628.0.63225.0.1426204800000.avro 
 
What the desire behavior is to have temp directory resides under final destination _temporary folder and fs.rename will work within the volume. Having to move from Volume A to Volume B is not desire behavior (etl.execution.base.path to etl.destination.path.path ( I cannot be same because metadata must be found by camus job and also time bounty each of messages due to lag in the Kafka data pipeline. 
 
data/tracking/AdOptimizationEvent/hourly/2015/03/12/16/_temporary/attempt_1424755100717_178507_m_000000_1/data.AdOptimizationEvent.0.0.1426204800000-m-00000.avro 
 
data/tracking/AdOptimizationEvent/hourly/2015/03/12/17/_temporary/attempt_1424755100717_178507_m_000000_2/data.AdOptimizationEvent.0.0.1426204800000-m-00000.avro 
 
data/tracking/AdOptimizationEvent/hourly/2015/03/12/18_temporary/attempt_1424755100717_178507_m_000000_3/data.AdOptimizationEvent.0.0.1426204800000-m-00000.avro 
 
I have made short term solve by using kafka --> copy _metadata _temp dir -> copy again in commit to  final destination _temp folder -> then rename to final target name.  
 
Again, this has overhead and not perfect solution as you pointed out: 
Please refer to https://github.com/bmistry13/kafka-trunk-producer/blob/master/FIX_EOF for the fix (ignore the pom change and also please let me know your feedback try to solve EOF/un-terminated files, data loss and (sequence file "empty" string appends) etc. I would really appropriate your feedback. Ideally, I would have class injection that would do the commit rather than the flag) 
 
So perfect solution is to a have *_temporary* folder under final destination, but only commit a file (rename when mapper is done and delete if mapper task is killed but cannot delete _temporary because other mapper may still be writing in the same path  _temporary or have __temporary_task_iD so no path collision hence each mapper can delete its temp folder..). 

Please let me know what you think about it.

Thanks, 
Bhavesh

**Comment by bmistry13** [comment]
@HenryCaiHaiying ,

About the counter,  I have this CamusJob.startTiming("some-metrics")  does not report on console.   I am doting this in OutputCommitter ?  Does counter propagate from each task to main CamusJob ?  

Please see the line  https://github.com/bmistry13/kafka-trunk-producer/blob/master/FIX_EOF#L753 and  https://github.com/bmistry13/kafka-trunk-producer/blob/master/FIX_EOF#L874

Any input or feedback are welcome.

Thanks,
Bhavesh 

Thanks,
Bhavesh

**Comment by bmistry13** [comment]
Any feedback on changes ?   Also, what is best way to track and/publish metric on console (previous comment).

Thanks,
Bhavesh

**Comment by bmistry13** [comment]
@zliu41 @HenryCaiHaiying  @Kaiserchen ,

I will be attending the Kafka meetup today (Tuesday, March 24, 2015) @ 6PM.  Do you guys want to sync-up for 30 minutes for a meeting before meetup ?  

Thanks,
Bhavesh
