### ISSUE TITLE
ArrayIndexOutOfBoundsException issue when LeaderNotAvailableException 

### ISSUE THREAD

**Issue by bmistry13** [linkedin/camus#190]
Hi Camus Team,

Please let me know if this issue is fixed or not I just compare the line # but with code but it is not matching so I just wanted to know if this is fixed.  If Yes, Please let me know commit id.

Thanks,
Bhavesh 

2015-03-11 17:29:14 INFO: com.linkedin.camus.etl.kafka.CamusJob - Skipping the creation of ETL request for Topic : TOPIC_NAME and Partition : 31 Exception : kafka.common.LeaderNotAvailableException=/JOB_ID
   666	Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
   667		at com.linkedin.camus.etl.kafka.mapred.EtlInputFormat.fetchLatestOffsetAndCreateEtlRequests(EtlInputFormat.java:187)
   668		at com.linkedin.camus.etl.kafka.mapred.EtlInputFormat.getSplits(EtlInputFormat.java:315)
   669		at org.apache.hadoop.mapred.JobClient.writeNewSplits(JobClient.java:1033)
   670		at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1050)
   671		at org.apache.hadoop.mapred.JobClient.access$500(JobClient.java:173)
   672		at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:934)
   673		at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:885)
   674		at java.security.AccessController.doPrivileged(Native Method)
   675		at javax.security.auth.Subject.doAs(Subject.java:396)
   676		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1127)
   677		at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:885)
   678		at org.apache.hadoop.mapreduce.Job.submit(Job.java:573)
   679		at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:318)
   680		at com.linkedin.camus.etl.kafka.CamusJob.run(CamusJob.java:646)
   681		at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
   682		at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
   683		at com.linkedin.camus.etl.kafka.CamusJob.main(CamusJob.java:610)

**Comment by HenryCaiHaiying** [comment]
Can you try the latest code?  I think this is fixed already.

________________________________

**Comment by bmistry13** [comment]
I can not since we are on Hadoop 1.x.x API.  So can you please let me know the commit id that fixed and I will have to port it.

Thanks,
Bhavesh

**Comment by HenryCaiHaiying** [comment]
I thought the code on master branch more or less works with hadoop 1 (maybe just need to change a few hadoop co-ordinates in pom.xml)

________________________________

**Comment by bmistry13** [comment]
@HenryCaiHaiying ,

I was able to port it to Hadoop 1.X.

Thanks,
Bhavesh
