### ISSUE TITLE
KafkaReader query to why we store in the etlkey msgAndOffset.offset() + 1

### ISSUE THREAD

**Issue by michaelandrepearce** [linkedin/camus#194]
Hi

In com.linkedin.camus.etl.kafka.common.KafkaReader

Why on storing in the EtlKey, we store to the field EtlKey.offset is it the actual kafka msg offset increment of 1? Surely this should be the actual message's offset as the name of the field portrays. Is this working round some bug?

      key.set(kafkaRequest.getTopic(), kafkaRequest.getLeaderId(), kafkaRequest.getPartition(), currentOffset,
          msgAndOffset.offset() + 1, message.checksum());

Cheers
Mike

**Comment by HenryCaiHaiying** [comment]
I haven't really traced that offset range, I think this probably just means that's the next offset to be fetched.

**Comment by michaelandrepearce** [comment]
I'm looking at how i could possible store the original message offset (and payload) with our message, by taking the stored offset and partition off the etlkey. But I've noticed the offset is always out by one, which i tracked to this.

Any objections in suggesting to rename the field in the key to nextOffset, so it is more obvious? the name offset is misleading. 

The other is keep it named as is storing the actual offset, and where used to get the nextOffset count to at that place do the increment.
