### ISSUE TITLE
JSON to AVRO conversion from Camus 

### ISSUE THREAD

**Issue by santosh-d3vpl3x** [linkedin/camus#195]
Hi there

Camus should be able to consume JSON messages and convert them into the AVRO with the help schema in schema repository. I have forked the master and made changes to cater this requirements. 

I would like to submit merge request for the same. Please have a look at codebase at https://github.com/santosh-d3vpl3x/camus

Class which acts as converter is, [JSONToAvroMessageDecoder.java](https://github.com/santosh-d3vpl3x/camus/blob/master/camus-kafka-coders/src/main/java/com/linkedin/camus/etl/kafka/coders/JSONToAvroMessageDecoder.java)

**Comment by HenryCaiHaiying** [comment]
- The code indentation doesn't look nice, can you do either 4-space or 2-space indentation?  
- There is hard-coded template field id: "tpl" in the code
- I think the code seems always require you have the timestamp field in the message before it processed 'tpl' field, is this expected?

**Comment by santosh-d3vpl3x** [comment]
I have changed the code with latest commit. Nope, timestamp field is not necessary and it was optional. But,I have removed it entirely from the code. It was there for datatype compatibility between JSON timestamp and AVRO long.

And, I hope that changed indentation does not put your eyes in agony.
