### ISSUE TITLE
Kafka Blacklist topics specified with regex?

### ISSUE THREAD

**Issue by alexmc6** [linkedin/camus#206]
I assumed that I could specify blacklists (and white lists) with wildcarded regexs. This does not seem to be working. Are they supposed to work? If not then can we have them as a new feature please? (I suppose we could supply a patch :-)

eg

kafka.blacklist.topics=DATA.BAD*
or
kafka.whitelist.topics=DATA.GOOD*

Also it is not clear whether I am supposed to use the original Kafka topic name with dots, or the Camus variant with underscores instead.

**Comment by zliu41** [comment]
Hi @alexmc6 
It should work. `EtlInputFormat.createTopicRegEx()` creates a regex that supports wildcard. The following should print true:
   `HashSet<String> s = new HashSet<String>();
    s.add("DATA.BAD.*");
    String regex = new EtlInputFormat().createTopicRegEx(s);
    System.out.println(Pattern.matches(regex, "DATA.BAD.AAA"));`

**Comment by alexmc6** [comment]
Thanks. I will triple check it and put in a full issue if it is still not working.
