### ISSUE TITLE
Creating a Release version

### ISSUE THREAD

**Issue by CJ-Lassila** [linkedin/camus#229]
Do you guys plan on creating a release of Camus? or does one currently exist elsewhere? I would like to use Camus as a dependency but my private repository does not allow outside snapshots to be used.

**Comment by akursar** [comment]
@CJ-Lassila - Have you checked out Confluent's distro, http://confluent.io/docs/current/installation.html#jars-via-maven-repository

**Comment by CJ-Lassila** [comment]
This should work for the time being, thank you! Any chance you guys will have this in the Maven Central repo?
