### ISSUE TITLE
NPE in camus hourly cleaner and daily cleaner

### ISSUE THREAD

**Issue by HenryCaiHaiying** [linkedin/camus#94]
When I run the camus-clean-hourly it failed with NPE in CamusHourlyCleaner:

31-07-2014 22:57:06 PDT camus-clean-hourly ERROR - Caused by: java.lang.NullPointerException
31-07-2014 22:57:06 PDT camus-clean-hourly ERROR - 	at com.linkedin.camus.sweeper.CamusHourlyCleaner.run(CamusHourlyCleaner.java:74)
31-07-2014 22:57:06 PDT camus-clean-hourly ERROR - 	at com.linkedin.camus.local.sweeper.CamusHourlyCleanerJob.run(CamusHourlyCleanerJob.java:30)

Line 74 is this:

    String fromLocation = (String) props.getProperty("camus.sweeper.source.dir");

From the code, looks like 'props' is never initialized in the class.

**Comment by erikvanoosten** [comment]
Can be closed as `CamusHourlyCleaner` no longer exists.
